---
title: "p8105_hw5_cm3341"
author: "Carolina Montes Garcia"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
set.seed(1)

```



## Problem 2

Create a function that generates values for a normal distribution and a two sided t-test.
```{r}
sim_mean_sd = function(n = 30, mu, sigma = 5) {
  
  sim_data = rnorm(n, mu, sigma)

  t_test = t.test(sim_data, y = NULL, mu = mu, alternative = "two.sided", conf.level = 0.95) %>% 
    broom::tidy() %>% 
    janitor::clean_names() %>% 
    select(p_value)

 out_df = 
   tibble(
    mu_hat = mu,
    p_value = t_test$p_value
    )

 return(out_df)
}
```

Now I simulate 
```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_mean_sd(30, 0, 5)
}

sim_results = bind_rows(output)


```

Now I iterate the function for different mu values.

```{r}

sim_res = 
  expand_grid(
    mu = c(1, 2, 3, 4, 5, 6),
    iter = 1:50
  ) %>%  
  mutate(samp_res = map(mu, \(x) sim_mean_sd(n = 30, x, sigma = 5))   ) %>%  
  unnest(samp_res) %>% 
  select(mu, p_value)

```

